import {useState,useEffect} from 'react';
import {recordEnglish,englishApi} from '../utils/platformStorage';
import {sendChatCompletion} from '../utils/aiClient';
import {loadAiConfig} from '../utils/aiConfigStorage';
declare global { interface Window {createStudyImagePicker:(element:HTMLElement)=>{ids:()=>string[];busy:()=>boolean;clear:()=>void};studyImageIds?:string[];platformToast?:(message:string)=>void;} }
export function StudyBridge({year,context,onReview}:{year:string;context:string;onReview:()=>void}) {
  const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[number,setNumber]=useState(Number(new URLSearchParams(location.search).get('note')) || 21),[note,setNote]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{const box=document.getElementById('english-images')!;const picker=window.createStudyImagePicker(box); const sync=()=>{window.studyImageIds=picker.ids();};box.addEventListener('study:images',sync);sync();return()=>{box.removeEventListener('study:images',sync);window.studyImageIds=[];};},[context]);
  useEffect(()=>{let active=true;englishApi(`/note?sourceId=${year}:${number}`).then(v=>{if(active)setNote(v.text || '');}).catch(()=>{});return()=>{active=false;};},[year,number]);
  async function ask(){if(busy)return;setBusy(true);try{setAnswer(await sendChatCompletion(loadAiConfig(),[{role:'system',content:'你是考研英语学习助手。讲清词汇、语法和解题方法，图片看不清请说明。'},{role:'user',content:question || '请讲解图片里的英语问题。'}]));}catch(e){setAnswer((e as Error).message);}finally{setBusy(false);}}
  async function saveNote(){try{await recordEnglish('/note',{sourceId:`${year}:${number}`,text:note});setMessage('笔记已保存到学习档案');}catch(e){setMessage((e as Error).message);}}
  return <section className="english-bridge"><div className="english-bridge-head"><strong>英语学习联动</strong><div><button type="button" onClick={onReview}>词汇复习</button><a href="/growth">每日目标与成长积分 →</a></div></div><details><summary>AI 图片附件、英语答疑与学习笔记</summary><p>题目与解析来自导入的英语资料；AI 批阅为学习参考，请结合原题核对。</p><p>本页 AI 批阅、翻译和答疑共用图片附件。每次最多 3 张，每张不超过 5 MB。</p><div id="english-images" key={context}></div><div className="english-bridge-fields"><div><label htmlFor="english-question">英语问题</label><textarea id="english-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={4000} placeholder="输入问题，或上传题目、作文图片"/><button type="button" onClick={ask} disabled={busy}>{busy?'正在答疑…':'发送给 AI'}</button><p className="english-ai-answer" role="status">{answer}</p></div><div><label htmlFor="english-note-number">{year} 年第 <input id="english-note-number" type="number" min="1" max="52" value={number} onChange={e=>setNumber(Number(e.target.value))}/> 题笔记</label><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={10000} placeholder="记录自己的思考，至少 10 字可领取笔记奖励" aria-label="英语学习笔记"/><button type="button" onClick={saveNote}>保存笔记</button><p role="status">{message}</p></div></div></details></section>;
}
